package com.bubli.agent.type;

public enum AgentJobType {
	ANALYZE_RESOURCE,
	GENERATE_REQUIREMENTS,
	GENERATE_WBS,
	GENERATE_TASKS,
	REVIEW_CONTRACT_DOCUMENTS,
	GENERATE_QUESTIONS,
	DAILY_SUMMARY,
	SUMMARIZE_DAY,
	SEARCH_RESOURCE,
	DRAFT_DOCUMENT

}
